baseURL = "http://ferdbold.com/"
title = "ferdbold | Frédéric Bolduc"
theme = "pulp"
languageCode = "fr-CA"

[params]
  author = "Frédéric Bolduc"
  description = "Gamedev. LARP. Ananas sur la pizza. Bonjour/Hi."
  avatar = "avatar.jpg"

[[menu.main]]
  identifier = "blog"
  pre = "Blog"
  url = "/blog/"
  weight = 10

[[menu.main]]
  identifier = "projects"
  pre = "My work"
  url = "/work/"
  weight = 20

[[menu.main]]
  identifier = "talks"
  pre = "Talks"
  url = "/talk/"
  weight = 30

[[menu.main]]
  identifier = "about"
  pre = "About"
  url = "/about/"
  weight = 40

[[menu.social]]
  identifier = "twitter"
  pre = "<i class='fab fa-twitter fa-lg'></i>"
  url = "https://twitter.com/itsferdbold"
  weight = 10

[[menu.social]]
  identifier = "github"
  pre = "<i class='fab fa-github fa-lg'></i>"
  url = "https://github.com/ferdbold"
  weight = 20

[[menu.social]]
  identifier = "linkedin"
  pre = "<i class='fab fa-linkedin-in fa-lg'></i>"
  url = "https://linkedin.com/in/bolducfrederic"
  weight = 30

[[menu.social]]
  identifier = "email"
  pre = "<i class='fa fa-envelope fa-lg'></i>"
  url = "mailto:me@ferdbold.com"
  weight = 40
